// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: job-request.proto

package jobrequestpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	BudgetMin     float64                `protobuf:"fixed64,7,opt,name=budget_min,json=budgetMin,proto3" json:"budget_min,omitempty"`
	BudgetMax     float64                `protobuf:"fixed64,8,opt,name=budget_max,json=budgetMax,proto3" json:"budget_max,omitempty"`
	ScheduledAt   string                 `protobuf:"bytes,9,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // open | closed | cancelled
	ResponseCount int32                  `protobuf:"varint,11,opt,name=response_count,json=responseCount,proto3" json:"response_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PhotoUrls     []string               `protobuf:"bytes,14,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_job_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *JobRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *JobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *JobRequest) GetBudgetMin() float64 {
	if x != nil {
		return x.BudgetMin
	}
	return 0
}

func (x *JobRequest) GetBudgetMax() float64 {
	if x != nil {
		return x.BudgetMax
	}
	return 0
}

func (x *JobRequest) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

func (x *JobRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobRequest) GetResponseCount() int32 {
	if x != nil {
		return x.ResponseCount
	}
	return 0
}

func (x *JobRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *JobRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *JobRequest) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

type JobRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobRequestId  int64                  `protobuf:"varint,2,opt,name=job_request_id,json=jobRequestId,proto3" json:"job_request_id,omitempty"`
	ProviderId    int64                  `protobuf:"varint,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProposedPrice float64                `protobuf:"fixed64,4,opt,name=proposed_price,json=proposedPrice,proto3" json:"proposed_price,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	EstimatedDays int32                  `protobuf:"varint,6,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // pending | accepted | rejected | withdrawn
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequestResponse) Reset() {
	*x = JobRequestResponse{}
	mi := &file_job_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequestResponse) ProtoMessage() {}

func (x *JobRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequestResponse.ProtoReflect.Descriptor instead.
func (*JobRequestResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{1}
}

func (x *JobRequestResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobRequestResponse) GetJobRequestId() int64 {
	if x != nil {
		return x.JobRequestId
	}
	return 0
}

func (x *JobRequestResponse) GetProviderId() int64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *JobRequestResponse) GetProposedPrice() float64 {
	if x != nil {
		return x.ProposedPrice
	}
	return 0
}

func (x *JobRequestResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *JobRequestResponse) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

func (x *JobRequestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobRequestResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *JobRequestResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateJobRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	BudgetMin     float64                `protobuf:"fixed64,5,opt,name=budget_min,json=budgetMin,proto3" json:"budget_min,omitempty"`
	BudgetMax     float64                `protobuf:"fixed64,6,opt,name=budget_max,json=budgetMax,proto3" json:"budget_max,omitempty"`
	ScheduledAt   string                 `protobuf:"bytes,7,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	PhotoUrls     []string               `protobuf:"bytes,8,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequestRequest) Reset() {
	*x = CreateJobRequestRequest{}
	mi := &file_job_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequestRequest) ProtoMessage() {}

func (x *CreateJobRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequestRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobRequestRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateJobRequestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateJobRequestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateJobRequestRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateJobRequestRequest) GetBudgetMin() float64 {
	if x != nil {
		return x.BudgetMin
	}
	return 0
}

func (x *CreateJobRequestRequest) GetBudgetMax() float64 {
	if x != nil {
		return x.BudgetMax
	}
	return 0
}

func (x *CreateJobRequestRequest) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

func (x *CreateJobRequestRequest) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

type CreateJobRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequest    *JobRequest            `protobuf:"bytes,1,opt,name=job_request,json=jobRequest,proto3" json:"job_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequestResponse) Reset() {
	*x = CreateJobRequestResponse{}
	mi := &file_job_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequestResponse) ProtoMessage() {}

func (x *CreateJobRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateJobRequestResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{3}
}

func (x *CreateJobRequestResponse) GetJobRequest() *JobRequest {
	if x != nil {
		return x.JobRequest
	}
	return nil
}

type GetJobRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequestRequest) Reset() {
	*x = GetJobRequestRequest{}
	mi := &file_job_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequestRequest) ProtoMessage() {}

func (x *GetJobRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequestRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequestRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobRequestRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetJobRequestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequest    *JobRequest            `protobuf:"bytes,1,opt,name=job_request,json=jobRequest,proto3" json:"job_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequestResult) Reset() {
	*x = GetJobRequestResult{}
	mi := &file_job_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequestResult) ProtoMessage() {}

func (x *GetJobRequestResult) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequestResult.ProtoReflect.Descriptor instead.
func (*GetJobRequestResult) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobRequestResult) GetJobRequest() *JobRequest {
	if x != nil {
		return x.JobRequest
	}
	return nil
}

type ListJobRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobRequestsRequest) Reset() {
	*x = ListJobRequestsRequest{}
	mi := &file_job_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobRequestsRequest) ProtoMessage() {}

func (x *ListJobRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListJobRequestsRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobRequestsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListJobRequestsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListJobRequestsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListJobRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobRequestsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListJobRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequests   []*JobRequest          `protobuf:"bytes,1,rep,name=job_requests,json=jobRequests,proto3" json:"job_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobRequestsResponse) Reset() {
	*x = ListJobRequestsResponse{}
	mi := &file_job_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobRequestsResponse) ProtoMessage() {}

func (x *ListJobRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListJobRequestsResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobRequestsResponse) GetJobRequests() []*JobRequest {
	if x != nil {
		return x.JobRequests
	}
	return nil
}

type CancelJobRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequestRequest) Reset() {
	*x = CancelJobRequestRequest{}
	mi := &file_job_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequestRequest) ProtoMessage() {}

func (x *CancelJobRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequestRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequestRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{8}
}

func (x *CancelJobRequestRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CancelJobRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequestResponse) Reset() {
	*x = CancelJobRequestResponse{}
	mi := &file_job_request_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequestResponse) ProtoMessage() {}

func (x *CancelJobRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequestResponse.ProtoReflect.Descriptor instead.
func (*CancelJobRequestResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{9}
}

func (x *CancelJobRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RespondToJobRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequestId  int64                  `protobuf:"varint,1,opt,name=job_request_id,json=jobRequestId,proto3" json:"job_request_id,omitempty"`
	ProposedPrice float64                `protobuf:"fixed64,2,opt,name=proposed_price,json=proposedPrice,proto3" json:"proposed_price,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	EstimatedDays int32                  `protobuf:"varint,4,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToJobRequestRequest) Reset() {
	*x = RespondToJobRequestRequest{}
	mi := &file_job_request_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToJobRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToJobRequestRequest) ProtoMessage() {}

func (x *RespondToJobRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToJobRequestRequest.ProtoReflect.Descriptor instead.
func (*RespondToJobRequestRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{10}
}

func (x *RespondToJobRequestRequest) GetJobRequestId() int64 {
	if x != nil {
		return x.JobRequestId
	}
	return 0
}

func (x *RespondToJobRequestRequest) GetProposedPrice() float64 {
	if x != nil {
		return x.ProposedPrice
	}
	return 0
}

func (x *RespondToJobRequestRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RespondToJobRequestRequest) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

type RespondToJobRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *JobRequestResponse    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToJobRequestResponse) Reset() {
	*x = RespondToJobRequestResponse{}
	mi := &file_job_request_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToJobRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToJobRequestResponse) ProtoMessage() {}

func (x *RespondToJobRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToJobRequestResponse.ProtoReflect.Descriptor instead.
func (*RespondToJobRequestResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{11}
}

func (x *RespondToJobRequestResponse) GetResponse() *JobRequestResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListJobRequestResponsesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequestId  int64                  `protobuf:"varint,1,opt,name=job_request_id,json=jobRequestId,proto3" json:"job_request_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobRequestResponsesRequest) Reset() {
	*x = ListJobRequestResponsesRequest{}
	mi := &file_job_request_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobRequestResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobRequestResponsesRequest) ProtoMessage() {}

func (x *ListJobRequestResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobRequestResponsesRequest.ProtoReflect.Descriptor instead.
func (*ListJobRequestResponsesRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{12}
}

func (x *ListJobRequestResponsesRequest) GetJobRequestId() int64 {
	if x != nil {
		return x.JobRequestId
	}
	return 0
}

func (x *ListJobRequestResponsesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobRequestResponsesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListJobRequestResponsesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*JobRequestResponse  `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobRequestResponsesResponse) Reset() {
	*x = ListJobRequestResponsesResponse{}
	mi := &file_job_request_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobRequestResponsesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobRequestResponsesResponse) ProtoMessage() {}

func (x *ListJobRequestResponsesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobRequestResponsesResponse.ProtoReflect.Descriptor instead.
func (*ListJobRequestResponsesResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{13}
}

func (x *ListJobRequestResponsesResponse) GetResponses() []*JobRequestResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetJobRequestResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequestId  int64                  `protobuf:"varint,1,opt,name=job_request_id,json=jobRequestId,proto3" json:"job_request_id,omitempty"`
	ResponseId    int64                  `protobuf:"varint,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequestResponseRequest) Reset() {
	*x = GetJobRequestResponseRequest{}
	mi := &file_job_request_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequestResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequestResponseRequest) ProtoMessage() {}

func (x *GetJobRequestResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequestResponseRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequestResponseRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{14}
}

func (x *GetJobRequestResponseRequest) GetJobRequestId() int64 {
	if x != nil {
		return x.JobRequestId
	}
	return 0
}

func (x *GetJobRequestResponseRequest) GetResponseId() int64 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

type GetJobRequestResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *JobRequestResponse    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequestResponseResponse) Reset() {
	*x = GetJobRequestResponseResponse{}
	mi := &file_job_request_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequestResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequestResponseResponse) ProtoMessage() {}

func (x *GetJobRequestResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequestResponseResponse.ProtoReflect.Descriptor instead.
func (*GetJobRequestResponseResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{15}
}

func (x *GetJobRequestResponseResponse) GetResponse() *JobRequestResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type AcceptJobRequestResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequestId  int64                  `protobuf:"varint,1,opt,name=job_request_id,json=jobRequestId,proto3" json:"job_request_id,omitempty"`
	ResponseId    int64                  `protobuf:"varint,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ScheduledAt   string                 `protobuf:"bytes,8,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptJobRequestResponseRequest) Reset() {
	*x = AcceptJobRequestResponseRequest{}
	mi := &file_job_request_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptJobRequestResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptJobRequestResponseRequest) ProtoMessage() {}

func (x *AcceptJobRequestResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptJobRequestResponseRequest.ProtoReflect.Descriptor instead.
func (*AcceptJobRequestResponseRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{16}
}

func (x *AcceptJobRequestResponseRequest) GetJobRequestId() int64 {
	if x != nil {
		return x.JobRequestId
	}
	return 0
}

func (x *AcceptJobRequestResponseRequest) GetResponseId() int64 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

func (x *AcceptJobRequestResponseRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *AcceptJobRequestResponseRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AcceptJobRequestResponseRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AcceptJobRequestResponseRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AcceptJobRequestResponseRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AcceptJobRequestResponseRequest) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

type AcceptJobRequestResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequest    *JobRequest            `protobuf:"bytes,1,opt,name=job_request,json=jobRequest,proto3" json:"job_request,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptJobRequestResponseResponse) Reset() {
	*x = AcceptJobRequestResponseResponse{}
	mi := &file_job_request_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptJobRequestResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptJobRequestResponseResponse) ProtoMessage() {}

func (x *AcceptJobRequestResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptJobRequestResponseResponse.ProtoReflect.Descriptor instead.
func (*AcceptJobRequestResponseResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{17}
}

func (x *AcceptJobRequestResponseResponse) GetJobRequest() *JobRequest {
	if x != nil {
		return x.JobRequest
	}
	return nil
}

func (x *AcceptJobRequestResponseResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type WithdrawJobRequestResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRequestId  int64                  `protobuf:"varint,1,opt,name=job_request_id,json=jobRequestId,proto3" json:"job_request_id,omitempty"`
	ResponseId    int64                  `protobuf:"varint,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawJobRequestResponseRequest) Reset() {
	*x = WithdrawJobRequestResponseRequest{}
	mi := &file_job_request_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawJobRequestResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawJobRequestResponseRequest) ProtoMessage() {}

func (x *WithdrawJobRequestResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawJobRequestResponseRequest.ProtoReflect.Descriptor instead.
func (*WithdrawJobRequestResponseRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{18}
}

func (x *WithdrawJobRequestResponseRequest) GetJobRequestId() int64 {
	if x != nil {
		return x.JobRequestId
	}
	return 0
}

func (x *WithdrawJobRequestResponseRequest) GetResponseId() int64 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

type WithdrawJobRequestResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawJobRequestResponseResponse) Reset() {
	*x = WithdrawJobRequestResponseResponse{}
	mi := &file_job_request_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawJobRequestResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawJobRequestResponseResponse) ProtoMessage() {}

func (x *WithdrawJobRequestResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawJobRequestResponseResponse.ProtoReflect.Descriptor instead.
func (*WithdrawJobRequestResponseResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{19}
}

func (x *WithdrawJobRequestResponseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsRequest) Reset() {
	*x = GetAnalyticsRequest{}
	mi := &file_job_request_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsRequest) ProtoMessage() {}

func (x *GetAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{20}
}

type GetAnalyticsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalJobRequests     int64                  `protobuf:"varint,1,opt,name=total_job_requests,json=totalJobRequests,proto3" json:"total_job_requests,omitempty"`
	JobRequestsThisMonth int64                  `protobuf:"varint,2,opt,name=job_requests_this_month,json=jobRequestsThisMonth,proto3" json:"job_requests_this_month,omitempty"`
	OpenJobRequests      int64                  `protobuf:"varint,3,opt,name=open_job_requests,json=openJobRequests,proto3" json:"open_job_requests,omitempty"` // status=open
	ClosedJobRequests    int64                  `protobuf:"varint,4,opt,name=closed_job_requests,json=closedJobRequests,proto3" json:"closed_job_requests,omitempty"`
	CancelledJobRequests int64                  `protobuf:"varint,5,opt,name=cancelled_job_requests,json=cancelledJobRequests,proto3" json:"cancelled_job_requests,omitempty"`
	TotalResponses       int64                  `protobuf:"varint,6,opt,name=total_responses,json=totalResponses,proto3" json:"total_responses,omitempty"`
	ResponsesThisMonth   int64                  `protobuf:"varint,7,opt,name=responses_this_month,json=responsesThisMonth,proto3" json:"responses_this_month,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAnalyticsResponse) Reset() {
	*x = GetAnalyticsResponse{}
	mi := &file_job_request_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsResponse) ProtoMessage() {}

func (x *GetAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_request_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_job_request_proto_rawDescGZIP(), []int{21}
}

func (x *GetAnalyticsResponse) GetTotalJobRequests() int64 {
	if x != nil {
		return x.TotalJobRequests
	}
	return 0
}

func (x *GetAnalyticsResponse) GetJobRequestsThisMonth() int64 {
	if x != nil {
		return x.JobRequestsThisMonth
	}
	return 0
}

func (x *GetAnalyticsResponse) GetOpenJobRequests() int64 {
	if x != nil {
		return x.OpenJobRequests
	}
	return 0
}

func (x *GetAnalyticsResponse) GetClosedJobRequests() int64 {
	if x != nil {
		return x.ClosedJobRequests
	}
	return 0
}

func (x *GetAnalyticsResponse) GetCancelledJobRequests() int64 {
	if x != nil {
		return x.CancelledJobRequests
	}
	return 0
}

func (x *GetAnalyticsResponse) GetTotalResponses() int64 {
	if x != nil {
		return x.TotalResponses
	}
	return 0
}

func (x *GetAnalyticsResponse) GetResponsesThisMonth() int64 {
	if x != nil {
		return x.ResponsesThisMonth
	}
	return 0
}

var File_job_request_proto protoreflect.FileDescriptor

const file_job_request_proto_rawDesc = "" +
	"\n" +
	"\x11job-request.proto\x12\rjobrequest.v1\x1a\x1cgoogle/api/annotations.proto\"\xa7\x03\n" +
	"\n" +
	"JobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"budget_min\x18\a \x01(\x01R\tbudgetMin\x12\x1d\n" +
	"\n" +
	"budget_max\x18\b \x01(\x01R\tbudgetMax\x12!\n" +
	"\fscheduled_at\x18\t \x01(\tR\vscheduledAt\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12%\n" +
	"\x0eresponse_count\x18\v \x01(\x05R\rresponseCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\x0e \x03(\tR\tphotoUrls\"\xa9\x02\n" +
	"\x12JobRequestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\x0ejob_request_id\x18\x02 \x01(\x03R\fjobRequestId\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\x03R\n" +
	"providerId\x12%\n" +
	"\x0eproposed_price\x18\x04 \x01(\x01R\rproposedPrice\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12%\n" +
	"\x0eestimated_days\x18\x06 \x01(\x05R\restimatedDays\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x86\x02\n" +
	"\x17CreateJobRequestRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"budget_min\x18\x05 \x01(\x01R\tbudgetMin\x12\x1d\n" +
	"\n" +
	"budget_max\x18\x06 \x01(\x01R\tbudgetMax\x12!\n" +
	"\fscheduled_at\x18\a \x01(\tR\vscheduledAt\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\b \x03(\tR\tphotoUrls\"V\n" +
	"\x18CreateJobRequestResponse\x12:\n" +
	"\vjob_request\x18\x01 \x01(\v2\x19.jobrequest.v1.JobRequestR\n" +
	"jobRequest\"&\n" +
	"\x14GetJobRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Q\n" +
	"\x13GetJobRequestResult\x12:\n" +
	"\vjob_request\x18\x01 \x01(\v2\x19.jobrequest.v1.JobRequestR\n" +
	"jobRequest\"\x93\x01\n" +
	"\x16ListJobRequestsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"W\n" +
	"\x17ListJobRequestsResponse\x12<\n" +
	"\fjob_requests\x18\x01 \x03(\v2\x19.jobrequest.v1.JobRequestR\vjobRequests\")\n" +
	"\x17CancelJobRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x18CancelJobRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xaa\x01\n" +
	"\x1aRespondToJobRequestRequest\x12$\n" +
	"\x0ejob_request_id\x18\x01 \x01(\x03R\fjobRequestId\x12%\n" +
	"\x0eproposed_price\x18\x02 \x01(\x01R\rproposedPrice\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12%\n" +
	"\x0eestimated_days\x18\x04 \x01(\x05R\restimatedDays\"\\\n" +
	"\x1bRespondToJobRequestResponse\x12=\n" +
	"\bresponse\x18\x01 \x01(\v2!.jobrequest.v1.JobRequestResponseR\bresponse\"t\n" +
	"\x1eListJobRequestResponsesRequest\x12$\n" +
	"\x0ejob_request_id\x18\x01 \x01(\x03R\fjobRequestId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"b\n" +
	"\x1fListJobRequestResponsesResponse\x12?\n" +
	"\tresponses\x18\x01 \x03(\v2!.jobrequest.v1.JobRequestResponseR\tresponses\"e\n" +
	"\x1cGetJobRequestResponseRequest\x12$\n" +
	"\x0ejob_request_id\x18\x01 \x01(\x03R\fjobRequestId\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\x03R\n" +
	"responseId\"^\n" +
	"\x1dGetJobRequestResponseResponse\x12=\n" +
	"\bresponse\x18\x01 \x01(\v2!.jobrequest.v1.JobRequestResponseR\bresponse\"\x89\x02\n" +
	"\x1fAcceptJobRequestResponseRequest\x12$\n" +
	"\x0ejob_request_id\x18\x01 \x01(\x03R\fjobRequestId\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\x03R\n" +
	"responseId\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12!\n" +
	"\fscheduled_at\x18\b \x01(\tR\vscheduledAt\"y\n" +
	" AcceptJobRequestResponseResponse\x12:\n" +
	"\vjob_request\x18\x01 \x01(\v2\x19.jobrequest.v1.JobRequestR\n" +
	"jobRequest\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\"j\n" +
	"!WithdrawJobRequestResponseRequest\x12$\n" +
	"\x0ejob_request_id\x18\x01 \x01(\x03R\fjobRequestId\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\x03R\n" +
	"responseId\">\n" +
	"\"WithdrawJobRequestResponseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13GetAnalyticsRequest\"\xe8\x02\n" +
	"\x14GetAnalyticsResponse\x12,\n" +
	"\x12total_job_requests\x18\x01 \x01(\x03R\x10totalJobRequests\x125\n" +
	"\x17job_requests_this_month\x18\x02 \x01(\x03R\x14jobRequestsThisMonth\x12*\n" +
	"\x11open_job_requests\x18\x03 \x01(\x03R\x0fopenJobRequests\x12.\n" +
	"\x13closed_job_requests\x18\x04 \x01(\x03R\x11closedJobRequests\x124\n" +
	"\x16cancelled_job_requests\x18\x05 \x01(\x03R\x14cancelledJobRequests\x12'\n" +
	"\x0ftotal_responses\x18\x06 \x01(\x03R\x0etotalResponses\x120\n" +
	"\x14responses_this_month\x18\a \x01(\x03R\x12responsesThisMonth2\xb3\f\n" +
	"\x11JobRequestService\x12\x80\x01\n" +
	"\x10CreateJobRequest\x12&.jobrequest.v1.CreateJobRequestRequest\x1a'.jobrequest.v1.CreateJobRequestResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/job-requests\x12w\n" +
	"\rGetJobRequest\x12#.jobrequest.v1.GetJobRequestRequest\x1a\".jobrequest.v1.GetJobRequestResult\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/job-requests/{id}\x12z\n" +
	"\x0fListJobRequests\x12%.jobrequest.v1.ListJobRequestsRequest\x1a&.jobrequest.v1.ListJobRequestsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/job-requests\x12\x82\x01\n" +
	"\x10CancelJobRequest\x12&.jobrequest.v1.CancelJobRequestRequest\x1a'.jobrequest.v1.CancelJobRequestResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/job-requests/{id}\x12\xa2\x01\n" +
	"\x13RespondToJobRequest\x12).jobrequest.v1.RespondToJobRequestRequest\x1a*.jobrequest.v1.RespondToJobRequestResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/v1/job-requests/{job_request_id}/respond\x12\xad\x01\n" +
	"\x17ListJobRequestResponses\x12-.jobrequest.v1.ListJobRequestResponsesRequest\x1a..jobrequest.v1.ListJobRequestResponsesResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/job-requests/{job_request_id}/responses\x12\xb5\x01\n" +
	"\x15GetJobRequestResponse\x12+.jobrequest.v1.GetJobRequestResponseRequest\x1a,.jobrequest.v1.GetJobRequestResponseResponse\"A\x82\xd3\xe4\x93\x02;\x129/v1/job-requests/{job_request_id}/responses/{response_id}\x12\xc8\x01\n" +
	"\x18AcceptJobRequestResponse\x12..jobrequest.v1.AcceptJobRequestResponseRequest\x1a/.jobrequest.v1.AcceptJobRequestResponseResponse\"K\x82\xd3\xe4\x93\x02E:\x01*\"@/v1/job-requests/{job_request_id}/responses/{response_id}/accept\x12\xc4\x01\n" +
	"\x1aWithdrawJobRequestResponse\x120.jobrequest.v1.WithdrawJobRequestResponseRequest\x1a1.jobrequest.v1.WithdrawJobRequestResponseResponse\"A\x82\xd3\xe4\x93\x02;*9/v1/job-requests/{job_request_id}/responses/{response_id}\x12\x81\x01\n" +
	"\fGetAnalytics\x12\".jobrequest.v1.GetAnalyticsRequest\x1a#.jobrequest.v1.GetAnalyticsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/admin/job-requests/analyticsBAZ?github.com/bvbl1/masterhub-proto/golang/jobrequest;jobrequestpbb\x06proto3"

var (
	file_job_request_proto_rawDescOnce sync.Once
	file_job_request_proto_rawDescData []byte
)

func file_job_request_proto_rawDescGZIP() []byte {
	file_job_request_proto_rawDescOnce.Do(func() {
		file_job_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_request_proto_rawDesc), len(file_job_request_proto_rawDesc)))
	})
	return file_job_request_proto_rawDescData
}

var file_job_request_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_job_request_proto_goTypes = []any{
	(*JobRequest)(nil),                         // 0: jobrequest.v1.JobRequest
	(*JobRequestResponse)(nil),                 // 1: jobrequest.v1.JobRequestResponse
	(*CreateJobRequestRequest)(nil),            // 2: jobrequest.v1.CreateJobRequestRequest
	(*CreateJobRequestResponse)(nil),           // 3: jobrequest.v1.CreateJobRequestResponse
	(*GetJobRequestRequest)(nil),               // 4: jobrequest.v1.GetJobRequestRequest
	(*GetJobRequestResult)(nil),                // 5: jobrequest.v1.GetJobRequestResult
	(*ListJobRequestsRequest)(nil),             // 6: jobrequest.v1.ListJobRequestsRequest
	(*ListJobRequestsResponse)(nil),            // 7: jobrequest.v1.ListJobRequestsResponse
	(*CancelJobRequestRequest)(nil),            // 8: jobrequest.v1.CancelJobRequestRequest
	(*CancelJobRequestResponse)(nil),           // 9: jobrequest.v1.CancelJobRequestResponse
	(*RespondToJobRequestRequest)(nil),         // 10: jobrequest.v1.RespondToJobRequestRequest
	(*RespondToJobRequestResponse)(nil),        // 11: jobrequest.v1.RespondToJobRequestResponse
	(*ListJobRequestResponsesRequest)(nil),     // 12: jobrequest.v1.ListJobRequestResponsesRequest
	(*ListJobRequestResponsesResponse)(nil),    // 13: jobrequest.v1.ListJobRequestResponsesResponse
	(*GetJobRequestResponseRequest)(nil),       // 14: jobrequest.v1.GetJobRequestResponseRequest
	(*GetJobRequestResponseResponse)(nil),      // 15: jobrequest.v1.GetJobRequestResponseResponse
	(*AcceptJobRequestResponseRequest)(nil),    // 16: jobrequest.v1.AcceptJobRequestResponseRequest
	(*AcceptJobRequestResponseResponse)(nil),   // 17: jobrequest.v1.AcceptJobRequestResponseResponse
	(*WithdrawJobRequestResponseRequest)(nil),  // 18: jobrequest.v1.WithdrawJobRequestResponseRequest
	(*WithdrawJobRequestResponseResponse)(nil), // 19: jobrequest.v1.WithdrawJobRequestResponseResponse
	(*GetAnalyticsRequest)(nil),                // 20: jobrequest.v1.GetAnalyticsRequest
	(*GetAnalyticsResponse)(nil),               // 21: jobrequest.v1.GetAnalyticsResponse
}
var file_job_request_proto_depIdxs = []int32{
	0,  // 0: jobrequest.v1.CreateJobRequestResponse.job_request:type_name -> jobrequest.v1.JobRequest
	0,  // 1: jobrequest.v1.GetJobRequestResult.job_request:type_name -> jobrequest.v1.JobRequest
	0,  // 2: jobrequest.v1.ListJobRequestsResponse.job_requests:type_name -> jobrequest.v1.JobRequest
	1,  // 3: jobrequest.v1.RespondToJobRequestResponse.response:type_name -> jobrequest.v1.JobRequestResponse
	1,  // 4: jobrequest.v1.ListJobRequestResponsesResponse.responses:type_name -> jobrequest.v1.JobRequestResponse
	1,  // 5: jobrequest.v1.GetJobRequestResponseResponse.response:type_name -> jobrequest.v1.JobRequestResponse
	0,  // 6: jobrequest.v1.AcceptJobRequestResponseResponse.job_request:type_name -> jobrequest.v1.JobRequest
	2,  // 7: jobrequest.v1.JobRequestService.CreateJobRequest:input_type -> jobrequest.v1.CreateJobRequestRequest
	4,  // 8: jobrequest.v1.JobRequestService.GetJobRequest:input_type -> jobrequest.v1.GetJobRequestRequest
	6,  // 9: jobrequest.v1.JobRequestService.ListJobRequests:input_type -> jobrequest.v1.ListJobRequestsRequest
	8,  // 10: jobrequest.v1.JobRequestService.CancelJobRequest:input_type -> jobrequest.v1.CancelJobRequestRequest
	10, // 11: jobrequest.v1.JobRequestService.RespondToJobRequest:input_type -> jobrequest.v1.RespondToJobRequestRequest
	12, // 12: jobrequest.v1.JobRequestService.ListJobRequestResponses:input_type -> jobrequest.v1.ListJobRequestResponsesRequest
	14, // 13: jobrequest.v1.JobRequestService.GetJobRequestResponse:input_type -> jobrequest.v1.GetJobRequestResponseRequest
	16, // 14: jobrequest.v1.JobRequestService.AcceptJobRequestResponse:input_type -> jobrequest.v1.AcceptJobRequestResponseRequest
	18, // 15: jobrequest.v1.JobRequestService.WithdrawJobRequestResponse:input_type -> jobrequest.v1.WithdrawJobRequestResponseRequest
	20, // 16: jobrequest.v1.JobRequestService.GetAnalytics:input_type -> jobrequest.v1.GetAnalyticsRequest
	3,  // 17: jobrequest.v1.JobRequestService.CreateJobRequest:output_type -> jobrequest.v1.CreateJobRequestResponse
	5,  // 18: jobrequest.v1.JobRequestService.GetJobRequest:output_type -> jobrequest.v1.GetJobRequestResult
	7,  // 19: jobrequest.v1.JobRequestService.ListJobRequests:output_type -> jobrequest.v1.ListJobRequestsResponse
	9,  // 20: jobrequest.v1.JobRequestService.CancelJobRequest:output_type -> jobrequest.v1.CancelJobRequestResponse
	11, // 21: jobrequest.v1.JobRequestService.RespondToJobRequest:output_type -> jobrequest.v1.RespondToJobRequestResponse
	13, // 22: jobrequest.v1.JobRequestService.ListJobRequestResponses:output_type -> jobrequest.v1.ListJobRequestResponsesResponse
	15, // 23: jobrequest.v1.JobRequestService.GetJobRequestResponse:output_type -> jobrequest.v1.GetJobRequestResponseResponse
	17, // 24: jobrequest.v1.JobRequestService.AcceptJobRequestResponse:output_type -> jobrequest.v1.AcceptJobRequestResponseResponse
	19, // 25: jobrequest.v1.JobRequestService.WithdrawJobRequestResponse:output_type -> jobrequest.v1.WithdrawJobRequestResponseResponse
	21, // 26: jobrequest.v1.JobRequestService.GetAnalytics:output_type -> jobrequest.v1.GetAnalyticsResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_job_request_proto_init() }
func file_job_request_proto_init() {
	if File_job_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_request_proto_rawDesc), len(file_job_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_request_proto_goTypes,
		DependencyIndexes: file_job_request_proto_depIdxs,
		MessageInfos:      file_job_request_proto_msgTypes,
	}.Build()
	File_job_request_proto = out.File
	file_job_request_proto_goTypes = nil
	file_job_request_proto_depIdxs = nil
}
