// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: job-request.proto

package jobrequestpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobRequestService_CreateJobRequest_FullMethodName           = "/jobrequest.v1.JobRequestService/CreateJobRequest"
	JobRequestService_GetJobRequest_FullMethodName              = "/jobrequest.v1.JobRequestService/GetJobRequest"
	JobRequestService_ListJobRequests_FullMethodName            = "/jobrequest.v1.JobRequestService/ListJobRequests"
	JobRequestService_CancelJobRequest_FullMethodName           = "/jobrequest.v1.JobRequestService/CancelJobRequest"
	JobRequestService_RespondToJobRequest_FullMethodName        = "/jobrequest.v1.JobRequestService/RespondToJobRequest"
	JobRequestService_ListJobRequestResponses_FullMethodName    = "/jobrequest.v1.JobRequestService/ListJobRequestResponses"
	JobRequestService_GetJobRequestResponse_FullMethodName      = "/jobrequest.v1.JobRequestService/GetJobRequestResponse"
	JobRequestService_AcceptJobRequestResponse_FullMethodName   = "/jobrequest.v1.JobRequestService/AcceptJobRequestResponse"
	JobRequestService_WithdrawJobRequestResponse_FullMethodName = "/jobrequest.v1.JobRequestService/WithdrawJobRequestResponse"
)

// JobRequestServiceClient is the client API for JobRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobRequestServiceClient interface {
	CreateJobRequest(ctx context.Context, in *CreateJobRequestRequest, opts ...grpc.CallOption) (*CreateJobRequestResponse, error)
	GetJobRequest(ctx context.Context, in *GetJobRequestRequest, opts ...grpc.CallOption) (*GetJobRequestResult, error)
	ListJobRequests(ctx context.Context, in *ListJobRequestsRequest, opts ...grpc.CallOption) (*ListJobRequestsResponse, error)
	CancelJobRequest(ctx context.Context, in *CancelJobRequestRequest, opts ...grpc.CallOption) (*CancelJobRequestResponse, error)
	RespondToJobRequest(ctx context.Context, in *RespondToJobRequestRequest, opts ...grpc.CallOption) (*RespondToJobRequestResponse, error)
	ListJobRequestResponses(ctx context.Context, in *ListJobRequestResponsesRequest, opts ...grpc.CallOption) (*ListJobRequestResponsesResponse, error)
	GetJobRequestResponse(ctx context.Context, in *GetJobRequestResponseRequest, opts ...grpc.CallOption) (*GetJobRequestResponseResponse, error)
	AcceptJobRequestResponse(ctx context.Context, in *AcceptJobRequestResponseRequest, opts ...grpc.CallOption) (*AcceptJobRequestResponseResponse, error)
	WithdrawJobRequestResponse(ctx context.Context, in *WithdrawJobRequestResponseRequest, opts ...grpc.CallOption) (*WithdrawJobRequestResponseResponse, error)
}

type jobRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobRequestServiceClient(cc grpc.ClientConnInterface) JobRequestServiceClient {
	return &jobRequestServiceClient{cc}
}

func (c *jobRequestServiceClient) CreateJobRequest(ctx context.Context, in *CreateJobRequestRequest, opts ...grpc.CallOption) (*CreateJobRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobRequestResponse)
	err := c.cc.Invoke(ctx, JobRequestService_CreateJobRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobRequestServiceClient) GetJobRequest(ctx context.Context, in *GetJobRequestRequest, opts ...grpc.CallOption) (*GetJobRequestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobRequestResult)
	err := c.cc.Invoke(ctx, JobRequestService_GetJobRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobRequestServiceClient) ListJobRequests(ctx context.Context, in *ListJobRequestsRequest, opts ...grpc.CallOption) (*ListJobRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobRequestsResponse)
	err := c.cc.Invoke(ctx, JobRequestService_ListJobRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobRequestServiceClient) CancelJobRequest(ctx context.Context, in *CancelJobRequestRequest, opts ...grpc.CallOption) (*CancelJobRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobRequestResponse)
	err := c.cc.Invoke(ctx, JobRequestService_CancelJobRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobRequestServiceClient) RespondToJobRequest(ctx context.Context, in *RespondToJobRequestRequest, opts ...grpc.CallOption) (*RespondToJobRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondToJobRequestResponse)
	err := c.cc.Invoke(ctx, JobRequestService_RespondToJobRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobRequestServiceClient) ListJobRequestResponses(ctx context.Context, in *ListJobRequestResponsesRequest, opts ...grpc.CallOption) (*ListJobRequestResponsesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobRequestResponsesResponse)
	err := c.cc.Invoke(ctx, JobRequestService_ListJobRequestResponses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobRequestServiceClient) GetJobRequestResponse(ctx context.Context, in *GetJobRequestResponseRequest, opts ...grpc.CallOption) (*GetJobRequestResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobRequestResponseResponse)
	err := c.cc.Invoke(ctx, JobRequestService_GetJobRequestResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobRequestServiceClient) AcceptJobRequestResponse(ctx context.Context, in *AcceptJobRequestResponseRequest, opts ...grpc.CallOption) (*AcceptJobRequestResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptJobRequestResponseResponse)
	err := c.cc.Invoke(ctx, JobRequestService_AcceptJobRequestResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobRequestServiceClient) WithdrawJobRequestResponse(ctx context.Context, in *WithdrawJobRequestResponseRequest, opts ...grpc.CallOption) (*WithdrawJobRequestResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawJobRequestResponseResponse)
	err := c.cc.Invoke(ctx, JobRequestService_WithdrawJobRequestResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobRequestServiceServer is the server API for JobRequestService service.
// All implementations must embed UnimplementedJobRequestServiceServer
// for forward compatibility.
type JobRequestServiceServer interface {
	CreateJobRequest(context.Context, *CreateJobRequestRequest) (*CreateJobRequestResponse, error)
	GetJobRequest(context.Context, *GetJobRequestRequest) (*GetJobRequestResult, error)
	ListJobRequests(context.Context, *ListJobRequestsRequest) (*ListJobRequestsResponse, error)
	CancelJobRequest(context.Context, *CancelJobRequestRequest) (*CancelJobRequestResponse, error)
	RespondToJobRequest(context.Context, *RespondToJobRequestRequest) (*RespondToJobRequestResponse, error)
	ListJobRequestResponses(context.Context, *ListJobRequestResponsesRequest) (*ListJobRequestResponsesResponse, error)
	GetJobRequestResponse(context.Context, *GetJobRequestResponseRequest) (*GetJobRequestResponseResponse, error)
	AcceptJobRequestResponse(context.Context, *AcceptJobRequestResponseRequest) (*AcceptJobRequestResponseResponse, error)
	WithdrawJobRequestResponse(context.Context, *WithdrawJobRequestResponseRequest) (*WithdrawJobRequestResponseResponse, error)
	mustEmbedUnimplementedJobRequestServiceServer()
}

// UnimplementedJobRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobRequestServiceServer struct{}

func (UnimplementedJobRequestServiceServer) CreateJobRequest(context.Context, *CreateJobRequestRequest) (*CreateJobRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJobRequest not implemented")
}
func (UnimplementedJobRequestServiceServer) GetJobRequest(context.Context, *GetJobRequestRequest) (*GetJobRequestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobRequest not implemented")
}
func (UnimplementedJobRequestServiceServer) ListJobRequests(context.Context, *ListJobRequestsRequest) (*ListJobRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobRequests not implemented")
}
func (UnimplementedJobRequestServiceServer) CancelJobRequest(context.Context, *CancelJobRequestRequest) (*CancelJobRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJobRequest not implemented")
}
func (UnimplementedJobRequestServiceServer) RespondToJobRequest(context.Context, *RespondToJobRequestRequest) (*RespondToJobRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToJobRequest not implemented")
}
func (UnimplementedJobRequestServiceServer) ListJobRequestResponses(context.Context, *ListJobRequestResponsesRequest) (*ListJobRequestResponsesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobRequestResponses not implemented")
}
func (UnimplementedJobRequestServiceServer) GetJobRequestResponse(context.Context, *GetJobRequestResponseRequest) (*GetJobRequestResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobRequestResponse not implemented")
}
func (UnimplementedJobRequestServiceServer) AcceptJobRequestResponse(context.Context, *AcceptJobRequestResponseRequest) (*AcceptJobRequestResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptJobRequestResponse not implemented")
}
func (UnimplementedJobRequestServiceServer) WithdrawJobRequestResponse(context.Context, *WithdrawJobRequestResponseRequest) (*WithdrawJobRequestResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawJobRequestResponse not implemented")
}
func (UnimplementedJobRequestServiceServer) mustEmbedUnimplementedJobRequestServiceServer() {}
func (UnimplementedJobRequestServiceServer) testEmbeddedByValue()                           {}

// UnsafeJobRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobRequestServiceServer will
// result in compilation errors.
type UnsafeJobRequestServiceServer interface {
	mustEmbedUnimplementedJobRequestServiceServer()
}

func RegisterJobRequestServiceServer(s grpc.ServiceRegistrar, srv JobRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedJobRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobRequestService_ServiceDesc, srv)
}

func _JobRequestService_CreateJobRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).CreateJobRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_CreateJobRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).CreateJobRequest(ctx, req.(*CreateJobRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobRequestService_GetJobRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).GetJobRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_GetJobRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).GetJobRequest(ctx, req.(*GetJobRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobRequestService_ListJobRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).ListJobRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_ListJobRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).ListJobRequests(ctx, req.(*ListJobRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobRequestService_CancelJobRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).CancelJobRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_CancelJobRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).CancelJobRequest(ctx, req.(*CancelJobRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobRequestService_RespondToJobRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToJobRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).RespondToJobRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_RespondToJobRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).RespondToJobRequest(ctx, req.(*RespondToJobRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobRequestService_ListJobRequestResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobRequestResponsesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).ListJobRequestResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_ListJobRequestResponses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).ListJobRequestResponses(ctx, req.(*ListJobRequestResponsesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobRequestService_GetJobRequestResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequestResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).GetJobRequestResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_GetJobRequestResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).GetJobRequestResponse(ctx, req.(*GetJobRequestResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobRequestService_AcceptJobRequestResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptJobRequestResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).AcceptJobRequestResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_AcceptJobRequestResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).AcceptJobRequestResponse(ctx, req.(*AcceptJobRequestResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobRequestService_WithdrawJobRequestResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawJobRequestResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobRequestServiceServer).WithdrawJobRequestResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobRequestService_WithdrawJobRequestResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobRequestServiceServer).WithdrawJobRequestResponse(ctx, req.(*WithdrawJobRequestResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobRequestService_ServiceDesc is the grpc.ServiceDesc for JobRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobrequest.v1.JobRequestService",
	HandlerType: (*JobRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJobRequest",
			Handler:    _JobRequestService_CreateJobRequest_Handler,
		},
		{
			MethodName: "GetJobRequest",
			Handler:    _JobRequestService_GetJobRequest_Handler,
		},
		{
			MethodName: "ListJobRequests",
			Handler:    _JobRequestService_ListJobRequests_Handler,
		},
		{
			MethodName: "CancelJobRequest",
			Handler:    _JobRequestService_CancelJobRequest_Handler,
		},
		{
			MethodName: "RespondToJobRequest",
			Handler:    _JobRequestService_RespondToJobRequest_Handler,
		},
		{
			MethodName: "ListJobRequestResponses",
			Handler:    _JobRequestService_ListJobRequestResponses_Handler,
		},
		{
			MethodName: "GetJobRequestResponse",
			Handler:    _JobRequestService_GetJobRequestResponse_Handler,
		},
		{
			MethodName: "AcceptJobRequestResponse",
			Handler:    _JobRequestService_AcceptJobRequestResponse_Handler,
		},
		{
			MethodName: "WithdrawJobRequestResponse",
			Handler:    _JobRequestService_WithdrawJobRequestResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job-request.proto",
}
