// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: media.proto

package mediapb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	UploaderId    int64                  `protobuf:"varint,2,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`   // "provider_documents" | "service_photos" | "review_photos" | "avatar"
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`           // Full public URL — frontend uses this directly
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"` // Original filename
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 string — simpler than google.protobuf.Timestamp for now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItem.ProtoReflect.Descriptor instead.
func (*MediaItem) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaItem) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *MediaItem) GetUploaderId() int64 {
	if x != nil {
		return x.UploaderId
	}
	return 0
}

func (x *MediaItem) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *MediaItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaItem) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MediaItem) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Note: actual file bytes are NOT in this proto message.
// The gRPC-gateway receives a multipart HTTP request, extracts the file,
// and passes the metadata fields here. The file content travels as bytes
// through the gateway layer before hitting the gRPC handler.
// uploader_id is never sent by client — always extracted from JWT.
type UploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMediaRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *UploadMediaRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadMediaRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaItem             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMediaResponse) GetMedia() *MediaItem {
	if x != nil {
		return x.Media
	}
	return nil
}

type FileInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInput) Reset() {
	*x = FileInput{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInput) ProtoMessage() {}

func (x *FileInput) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInput.ProtoReflect.Descriptor instead.
func (*FileInput) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *FileInput) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadManyMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // same context for all files in one batch
	Files         []*FileInput           `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadManyMediaRequest) Reset() {
	*x = UploadManyMediaRequest{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadManyMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadManyMediaRequest) ProtoMessage() {}

func (x *UploadManyMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadManyMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadManyMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *UploadManyMediaRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *UploadManyMediaRequest) GetFiles() []*FileInput {
	if x != nil {
		return x.Files
	}
	return nil
}

type UploadManyMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*MediaItem           `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadManyMediaResponse) Reset() {
	*x = UploadManyMediaResponse{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadManyMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadManyMediaResponse) ProtoMessage() {}

func (x *UploadManyMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadManyMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadManyMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

func (x *UploadManyMediaResponse) GetMedia() []*MediaItem {
	if x != nil {
		return x.Media
	}
	return nil
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaRequest) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaItem             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{7}
}

func (x *GetMediaResponse) GetMedia() *MediaItem {
	if x != nil {
		return x.Media
	}
	return nil
}

type GetManyMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaIds      []int64                `protobuf:"varint,1,rep,packed,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManyMediaRequest) Reset() {
	*x = GetManyMediaRequest{}
	mi := &file_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManyMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManyMediaRequest) ProtoMessage() {}

func (x *GetManyMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManyMediaRequest.ProtoReflect.Descriptor instead.
func (*GetManyMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{8}
}

func (x *GetManyMediaRequest) GetMediaIds() []int64 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

type GetManyMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*MediaItem           `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManyMediaResponse) Reset() {
	*x = GetManyMediaResponse{}
	mi := &file_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManyMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManyMediaResponse) ProtoMessage() {}

func (x *GetManyMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManyMediaResponse.ProtoReflect.Descriptor instead.
func (*GetManyMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetManyMediaResponse) GetMedia() []*MediaItem {
	if x != nil {
		return x.Media
	}
	return nil
}

type GetMyMediaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uploader_id extracted from JWT — not a request field
	Context       string `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // optional filter — empty string means return all contexts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyMediaRequest) Reset() {
	*x = GetMyMediaRequest{}
	mi := &file_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyMediaRequest) ProtoMessage() {}

func (x *GetMyMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMyMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyMediaRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type GetMyMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*MediaItem           `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyMediaResponse) Reset() {
	*x = GetMyMediaResponse{}
	mi := &file_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyMediaResponse) ProtoMessage() {}

func (x *GetMyMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMyMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{11}
}

func (x *GetMyMediaResponse) GetMedia() []*MediaItem {
	if x != nil {
		return x.Media
	}
	return nil
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMediaRequest) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteManyMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaIds      []int64                `protobuf:"varint,1,rep,packed,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManyMediaRequest) Reset() {
	*x = DeleteManyMediaRequest{}
	mi := &file_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyMediaRequest) ProtoMessage() {}

func (x *DeleteManyMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManyMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteManyMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteManyMediaRequest) GetMediaIds() []int64 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

type DeleteManyMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Deleted       int32                  `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`                             // how many were actually deleted
	FailedIds     []int64                `protobuf:"varint,3,rep,packed,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"` // IDs that failed — empty on full success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManyMediaResponse) Reset() {
	*x = DeleteManyMediaResponse{}
	mi := &file_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyMediaResponse) ProtoMessage() {}

func (x *DeleteManyMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManyMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteManyMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteManyMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteManyMediaResponse) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteManyMediaResponse) GetFailedIds() []int64 {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\bmedia.v1\x1a\x1cgoogle/api/annotations.proto\"\xcd\x01\n" +
	"\tMediaItem\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\x12\x1f\n" +
	"\vuploader_id\x18\x02 \x01(\x03R\n" +
	"uploaderId\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\x84\x01\n" +
	"\x12UploadMediaRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04dataJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05R\fcontent_typeR\n" +
	"size_bytes\"@\n" +
	"\x13UploadMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x01(\v2\x13.media.v1.MediaItemR\x05media\"a\n" +
	"\tFileInput\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04dataJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\fcontent_typeR\n" +
	"size_bytes\"]\n" +
	"\x16UploadManyMediaRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12)\n" +
	"\x05files\x18\x02 \x03(\v2\x13.media.v1.FileInputR\x05files\"D\n" +
	"\x17UploadManyMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x03(\v2\x13.media.v1.MediaItemR\x05media\",\n" +
	"\x0fGetMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\"=\n" +
	"\x10GetMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x01(\v2\x13.media.v1.MediaItemR\x05media\"2\n" +
	"\x13GetManyMediaRequest\x12\x1b\n" +
	"\tmedia_ids\x18\x01 \x03(\x03R\bmediaIds\"A\n" +
	"\x14GetManyMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x03(\v2\x13.media.v1.MediaItemR\x05media\"-\n" +
	"\x11GetMyMediaRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\"?\n" +
	"\x12GetMyMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x03(\v2\x13.media.v1.MediaItemR\x05media\"/\n" +
	"\x12DeleteMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\"/\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x16DeleteManyMediaRequest\x12\x1b\n" +
	"\tmedia_ids\x18\x01 \x03(\x03R\bmediaIds\"l\n" +
	"\x17DeleteManyMediaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\x05R\adeleted\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x03 \x03(\x03R\tfailedIds2\xf2\x05\n" +
	"\fMediaService\x12g\n" +
	"\vUploadMedia\x12\x1c.media.v1.UploadMediaRequest\x1a\x1d.media.v1.UploadMediaResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/media/upload\x12y\n" +
	"\x0fUploadManyMedia\x12 .media.v1.UploadManyMediaRequest\x1a!.media.v1.UploadManyMediaResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/media/upload/batch\x12_\n" +
	"\bGetMedia\x12\x19.media.v1.GetMediaRequest\x1a\x1a.media.v1.GetMediaResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/media/{media_id}\x12f\n" +
	"\fGetManyMedia\x12\x1d.media.v1.GetManyMediaRequest\x1a\x1e.media.v1.GetManyMediaResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/media/batch\x12Z\n" +
	"\n" +
	"GetMyMedia\x12\x1b.media.v1.GetMyMediaRequest\x1a\x1c.media.v1.GetMyMediaResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/media\x12h\n" +
	"\vDeleteMedia\x12\x1c.media.v1.DeleteMediaRequest\x1a\x1d.media.v1.DeleteMediaResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/media/{media_id}\x12o\n" +
	"\x0fDeleteManyMedia\x12 .media.v1.DeleteManyMediaRequest\x1a!.media.v1.DeleteManyMediaResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/media/batchB7Z5github.com/bvbl1/masterhub-proto/golang/media;mediapbb\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_media_proto_goTypes = []any{
	(*MediaItem)(nil),               // 0: media.v1.MediaItem
	(*UploadMediaRequest)(nil),      // 1: media.v1.UploadMediaRequest
	(*UploadMediaResponse)(nil),     // 2: media.v1.UploadMediaResponse
	(*FileInput)(nil),               // 3: media.v1.FileInput
	(*UploadManyMediaRequest)(nil),  // 4: media.v1.UploadManyMediaRequest
	(*UploadManyMediaResponse)(nil), // 5: media.v1.UploadManyMediaResponse
	(*GetMediaRequest)(nil),         // 6: media.v1.GetMediaRequest
	(*GetMediaResponse)(nil),        // 7: media.v1.GetMediaResponse
	(*GetManyMediaRequest)(nil),     // 8: media.v1.GetManyMediaRequest
	(*GetManyMediaResponse)(nil),    // 9: media.v1.GetManyMediaResponse
	(*GetMyMediaRequest)(nil),       // 10: media.v1.GetMyMediaRequest
	(*GetMyMediaResponse)(nil),      // 11: media.v1.GetMyMediaResponse
	(*DeleteMediaRequest)(nil),      // 12: media.v1.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),     // 13: media.v1.DeleteMediaResponse
	(*DeleteManyMediaRequest)(nil),  // 14: media.v1.DeleteManyMediaRequest
	(*DeleteManyMediaResponse)(nil), // 15: media.v1.DeleteManyMediaResponse
}
var file_media_proto_depIdxs = []int32{
	0,  // 0: media.v1.UploadMediaResponse.media:type_name -> media.v1.MediaItem
	3,  // 1: media.v1.UploadManyMediaRequest.files:type_name -> media.v1.FileInput
	0,  // 2: media.v1.UploadManyMediaResponse.media:type_name -> media.v1.MediaItem
	0,  // 3: media.v1.GetMediaResponse.media:type_name -> media.v1.MediaItem
	0,  // 4: media.v1.GetManyMediaResponse.media:type_name -> media.v1.MediaItem
	0,  // 5: media.v1.GetMyMediaResponse.media:type_name -> media.v1.MediaItem
	1,  // 6: media.v1.MediaService.UploadMedia:input_type -> media.v1.UploadMediaRequest
	4,  // 7: media.v1.MediaService.UploadManyMedia:input_type -> media.v1.UploadManyMediaRequest
	6,  // 8: media.v1.MediaService.GetMedia:input_type -> media.v1.GetMediaRequest
	8,  // 9: media.v1.MediaService.GetManyMedia:input_type -> media.v1.GetManyMediaRequest
	10, // 10: media.v1.MediaService.GetMyMedia:input_type -> media.v1.GetMyMediaRequest
	12, // 11: media.v1.MediaService.DeleteMedia:input_type -> media.v1.DeleteMediaRequest
	14, // 12: media.v1.MediaService.DeleteManyMedia:input_type -> media.v1.DeleteManyMediaRequest
	2,  // 13: media.v1.MediaService.UploadMedia:output_type -> media.v1.UploadMediaResponse
	5,  // 14: media.v1.MediaService.UploadManyMedia:output_type -> media.v1.UploadManyMediaResponse
	7,  // 15: media.v1.MediaService.GetMedia:output_type -> media.v1.GetMediaResponse
	9,  // 16: media.v1.MediaService.GetManyMedia:output_type -> media.v1.GetManyMediaResponse
	11, // 17: media.v1.MediaService.GetMyMedia:output_type -> media.v1.GetMyMediaResponse
	13, // 18: media.v1.MediaService.DeleteMedia:output_type -> media.v1.DeleteMediaResponse
	15, // 19: media.v1.MediaService.DeleteManyMedia:output_type -> media.v1.DeleteManyMediaResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
