syntax = "proto3";

package location.v1;

option go_package = "github.com/bvbl1/masterhub-proto/golang/location;locationpb";

import "google/api/annotations.proto";

service LocationService {
  rpc CreateLocation(CreateLocationRequest) returns (CreateLocationResponse) {
    option (google.api.http) = {
      post: "/v1/locations"
      body: "*"
    };
  }

  rpc GetLocation(GetLocationRequest) returns (GetLocationResponse) {
    option (google.api.http) = {
      get: "/v1/locations/{id}"
    };
  }
}

message Location {
  int64  id        = 1;
  int64  user_id   = 2;
  string street    = 3;
  string city      = 4;
  string region    = 5;
  double latitude  = 6;
  double longitude = 7;
}

message CreateLocationRequest {
  string street    = 1;
  string city      = 2;
  string region    = 3;
  double latitude  = 4;
  double longitude = 5;
}

message CreateLocationResponse {
  Location location = 1;
}

message GetLocationRequest {
  int64 id = 1;
}

message GetLocationResponse {
  Location location = 1;
}